/*
 * Minimal sdkconfig.h stub for standalone FreeRTOS builds outside ESP-IDF.
 *
 * When the GCC_XTENSA_ESP32 FreeRTOS port is used without the ESP-IDF build
 * system, sdkconfig.h (normally auto-generated by ESP-IDF's Kconfig) is not
 * available.  This stub provides the minimum set of CONFIG_* symbols consumed
 * by the port headers and assembly sources so that the build succeeds.
 *
 * In a real ESP-IDF build (via idf.py), the generated sdkconfig.h is placed
 * earlier in the include path and shadows this file automatically.
 */

#ifndef SDKCONFIG_STUB_H
#define SDKCONFIG_STUB_H

/* Use Xtensa internal timer 0 as the FreeRTOS tick source.
 * Exactly one of CONFIG_FREERTOS_CORETIMER_0 / _1 must be defined. */
#define CONFIG_FREERTOS_CORETIMER_0    1

/* ISR interrupt-handler stack size in bytes.
 * 1792 is the ESP-IDF default and is already a multiple of the required
 * 16-byte stack alignment (configSTACK_ALIGNMENT). */
#define CONFIG_FREERTOS_ISR_STACKSIZE    1792

/* Target selection used by ESP-IDF Xtensa FreeRTOS port sources. */
#ifndef CONFIG_IDF_TARGET_ESP32S3
	#define CONFIG_IDF_TARGET_ESP32S3    1
#endif

/* Single-core standalone default for this build profile. */
#ifndef CONFIG_FREERTOS_NO_AFFINITY
	#define CONFIG_FREERTOS_NO_AFFINITY    -1
#endif

/* Minimum logging-related options consumed by esp_log.h macros. */
#define CONFIG_LOG_MAXIMUM_LEVEL            3
#define CONFIG_LOG_COLORS                   0
#define CONFIG_LOG_TIMESTAMP_SOURCE_RTOS    0
#define CONFIG_LOG_TIMESTAMP_SOURCE_SYSTEM  1

#endif /* SDKCONFIG_STUB_H */
