#pragma once

#ifndef CONFIG_IDF_TARGET_ESP32S3
#define CONFIG_IDF_TARGET_ESP32S3 1
#endif
#ifndef CONFIG_IDF_TARGET_ESP32
#define CONFIG_IDF_TARGET_ESP32 0
#endif
#ifndef CONFIG_IDF_TARGET_ESP32S2
#define CONFIG_IDF_TARGET_ESP32S2 0
#endif
#ifndef CONFIG_IDF_TARGET_ESP32C3
#define CONFIG_IDF_TARGET_ESP32C3 0
#endif
#ifndef CONFIG_IDF_TARGET_ESP32H2
#define CONFIG_IDF_TARGET_ESP32H2 0
#endif

#ifndef CONFIG_FREERTOS_NO_AFFINITY
#define CONFIG_FREERTOS_NO_AFFINITY (-1)
#endif
#define CONFIG_FREERTOS_UNICORE 1
#define CONFIG_ESP_SYSTEM_SINGLE_CORE_MODE 1

#define CONFIG_FREERTOS_HZ 100
#define CONFIG_FREERTOS_ISR_STACKSIZE 1536

#define CONFIG_FREERTOS_CORETIMER_0 1
#define CONFIG_FREERTOS_CORETIMER_1 0
#define CONFIG_FREERTOS_SYSTICK_USES_CCOUNT 1
#define CONFIG_FREERTOS_SYSTICK_USES_SYSTIMER 0
#define CONFIG_FREERTOS_CORETIMER_SYSTIMER_LVL3 0

#define CONFIG_FREERTOS_TASK_FUNCTION_WRAPPER 0
#define CONFIG_FREERTOS_FPU_IN_ISR 0
#define CONFIG_FREERTOS_INTERRUPT_BACKTRACE 0
#define CONFIG_FREERTOS_RUN_TIME_STATS_USING_ESP_TIMER 0
#define CONFIG_FREERTOS_OPTIMIZED_SCHEDULER 0
#define CONFIG_FREERTOS_ASSERT_DISABLE 1
#define CONFIG_FREERTOS_ASSERT_ON_UNTESTED_FUNCTION 0

#define CONFIG_ESP32_DEBUG_OCDAWARE 0
#define CONFIG_ESP_INT_WDT 0
#define CONFIG_ESP_TASK_WDT 0
#define CONFIG_ESP_TASK_WDT_CHECK_IDLE_TASK_CPU0 0
#define CONFIG_ESP_TASK_WDT_CHECK_IDLE_TASK_CPU1 0
#define CONFIG_ESP_TASK_WDT_PANIC 0
#define CONFIG_ESP_TASK_WDT_TIMEOUT_S 5

#define CONFIG_PM_ENABLE 0
#define CONFIG_PM_TRACE 0

#define CONFIG_SPIRAM 0
#define CONFIG_SPIRAM_SUPPORT 0
#define CONFIG_SPIRAM_ALLOW_STACK_EXTERNAL_MEMORY 0
#define CONFIG_SPIRAM_MALLOC_RESERVE_INTERNAL 0
#define CONFIG_SPIRAM_SPEED_40M 0
#define CONFIG_SPIRAM_SPEED_80M 0
#define CONFIG_ESP32_SPIRAM_SUPPORT 0
#define CONFIG_ESP32S3_SPIRAM_SUPPORT 0

#define CONFIG_BTDM_CTRL_HLI 0
#define CONFIG_BTDM_CTRL_PINNED_TO_CORE 0
#define CONFIG_APPTRACE_SV_ENABLE 0

#define CONFIG_LOG_MAXIMUM_LEVEL 3

#define CONFIG_ESPTOOLPY_FLASHFREQ_26M 0
#define CONFIG_ESPTOOLPY_FLASHFREQ_40M 1
#define CONFIG_ESPTOOLPY_FLASHFREQ_80M 0
#define CONFIG_ESPTOOLPY_FLASHMODE_DIO 1
#define CONFIG_ESPTOOLPY_FLASHMODE_DOUT 0
#define CONFIG_ESPTOOLPY_FLASHMODE_QIO 0
#define CONFIG_ESPTOOLPY_FLASHMODE_QOUT 0
